name = "portifolio"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "dist/cloudflare"
entry-point = "dist/cloudflare"

[build]
command = "npm run build:cloudflare"
upload.format = "service-worker"

[build.upload]
format = "service-worker"

# Configurações para cache-control
[[headers]]
for = "/*"
[headers.values]
cache-control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/*.html"
[headers.values]
cache-control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/index.html"
[headers.values]
cache-control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*.js"
[headers.values]
cache-control = "public, max-age=86400, must-revalidate"

[[headers]]
for = "/*.css"
[headers.values]
cache-control = "public, max-age=86400, must-revalidate"

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = "public, max-age=31536000, immutable" 